// Reference: https://fonts.google.com/icons
// 参照先のSVGファイルから上下左右の余白(マージン)を削除しています。
export { default as SearchIcon } from '@/assets/icons/search.svg'
export { default as HomeIcon } from '@/assets/icons/home.svg'
export { default as HomeFillIcon } from '@/assets/icons/home-fill.svg'
export { default as MenuIcon } from '@/assets/icons/menu.svg'
export { default as CloseIcon } from '@/assets/icons/close.svg'
export { default as SettingsIcon } from '@/assets/icons/settings.svg'
export { default as SettingsFillIcon } from '@/assets/icons/settings-fill.svg'
export { default as CheckCircleIcon } from '@/assets/icons/check-circle.svg'
export { default as CheckCircleFillIcon } from '@/assets/icons/check-circle-fill.svg'
export { default as FavoriteIcon } from '@/assets/icons/favorite.svg'
export { default as FavoriteFillIcon } from '@/assets/icons/favorite-fill.svg'
export { default as AddIcon } from '@/assets/icons/add.svg'
export { default as DeleteIcon } from '@/assets/icons/delete.svg'
export { default as DeleteFillIcon } from '@/assets/icons/delete-fill.svg'
export { default as ArrowBackIcon } from '@/assets/icons/arrow-back.svg'
export { default as StarIcon } from '@/assets/icons/star.svg'
export { default as StarFillIcon } from '@/assets/icons/star-fill.svg'
export { default as ChevronRightIcon } from '@/assets/icons/chevron-right.svg'
export { default as LogoutIcon } from '@/assets/icons/logout.svg'
export { default as ArrowForwardIOSIcon } from '@/assets/icons/arrow-forward-iOS.svg'
export { default as AddCircleIcon } from '@/assets/icons/add-circle.svg'
export { default as AddCircleFillIcon } from '@/assets/icons/add-circle-fill.svg'
export { default as CancelIcon } from '@/assets/icons/cancel.svg'
export { default as CancelFillIcon } from '@/assets/icons/cancel-fill.svg'
export { default as ArrowBackIOSIcon } from '@/assets/icons/arrow-back-iOS.svg'
export { default as ArrowForwardIcon } from '@/assets/icons/arrow-forward.svg'
export { default as ArrowDropDownIcon } from '@/assets/icons/arrow-drop-down.svg'
export { default as MoreVertIcon } from '@/assets/icons/more-vert.svg'
export { default as CheckIcon } from '@/assets/icons/check.svg'
export { default as CheckBoxIcon } from '@/assets/icons/check-box.svg'
export { default as CheckBoxFillIcon } from '@/assets/icons/check-box-fill.svg'
export { default as OpenInNewIcon } from '@/assets/icons/open-in-new.svg'
export { default as ToggleOnIcon } from '@/assets/icons/toggle-on.svg'
export { default as ToggleOnFillIcon } from '@/assets/icons/toggle-on-fill.svg'
export { default as RefreshIcon } from '@/assets/icons/refresh.svg'
export { default as CheckBoxOutlineBlankIcon } from '@/assets/icons/check-box-outline-blank.svg'
export { default as LoginIcon } from '@/assets/icons/login.svg'
export { default as ChevronLeftIcon } from '@/assets/icons/chevron-left.svg'
export { default as RadioButtonUncheckedIcon } from '@/assets/icons/radio-button-unchecked.svg'
export { default as MoreHorizIcon } from '@/assets/icons/more-horiz.svg'
export { default as DownloadIcon } from '@/assets/icons/download.svg'
export { default as AppsIcon } from '@/assets/icons/apps.svg'
export { default as ArrowRightAltIcon } from '@/assets/icons/arrow-right-alt.svg'
export { default as RadioButtonCheckedIcon } from '@/assets/icons/radio-button-checked.svg'
export { default as FilterAltIcon } from '@/assets/icons/filter-alt.svg'
export { default as FilterAltFillIcon } from '@/assets/icons/filter-alt-fill.svg'
export { default as RemoveIcon } from '@/assets/icons/remove.svg'
export { default as BoltIcon } from '@/assets/icons/bolt.svg'
export { default as BoltFillIcon } from '@/assets/icons/bolt-fill.svg'
export { default as ArrowUpwardIcon } from '@/assets/icons/arrow-upward.svg'
export { default as ToggleOffIcon } from '@/assets/icons/toggle-off.svg'
export { default as ToggleOffFillIcon } from '@/assets/icons/toggle-off-fill.svg'
export { default as FilterListIcon } from '@/assets/icons/filter-list.svg'

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

export { default as DeleteForeverIcon } from '@/assets/icons/delete-forever.svg'
export { default as DeleteForeverFillIcon } from '@/assets/icons/delete-forever-fill.svg'
// export { default as AutorenewIcon } from '@/assets/icons/autorenew.svg'
// export { default as KeyIcon } from '@/assets/icons/key.svg'
// export { default as KeyFillIcon } from '@/assets/icons/key-fill.svg'
// export { default as BlockIcon } from '@/assets/icons/block.svg'
// export { default as SyncIcon } from '@/assets/icons/sync.svg'
// export { default as ArrowDownwardIcon } from '@/assets/icons/arrow-downward.svg'
// export { default as SortIcon } from '@/assets/icons/sort.svg'
// export { default as AddBoxIcon } from '@/assets/icons/add-box.svg'
// export { default as AddBoxFillIcon } from '@/assets/icons/add-box-fill.svg'

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

// export { default as ArrowBackIOSNewIcon } from '@/assets/icons/arrow-back-iOS-new.svg'
// export { default as RestartAltIcon } from '@/assets/icons/restart-alt.svg'
// export { default as ShoppingCartCheckoutIcon } from '@/assets/icons/shopping-cart-checkout.svg'
// export { default as MenuOpenIcon } from '@/assets/icons/menu-open.svg'
// export { default as ExpandCircleDownIcon } from '@/assets/icons/expand-circle-down.svg'
// export { default as ExpandCircleDownFillIcon } from '@/assets/icons/expand-circle-down-fill.svg'
// export { default as UndoIcon } from '@/assets/icons/undo.svg'
// export { default as BackspaceIcon } from '@/assets/icons/backspace.svg'
// export { default as BackspaceFillIcon } from '@/assets/icons/backspace-fill.svg'
// export { default as ArrowCircleRightIcon } from '@/assets/icons/arrow-circle-right.svg'
// export { default as ArrowCircleRightFillIcon } from '@/assets/icons/arrow-circle-right-fill.svg'
