// Reference: https://fonts.google.com/icons
// 参照先のSVGファイルから上下左右の余白(マージン)を削除しています。
export { default as SearchIcon } from '@/assets/icons/search.svg'
export { default as HomeIcon } from '@/assets/icons/home.svg'
export { default as HomeFillIcon } from '@/assets/icons/home-fill.svg'
export { default as MenuIcon } from '@/assets/icons/menu.svg'
export { default as CloseIcon } from '@/assets/icons/close.svg'
export { default as SettingsIcon } from '@/assets/icons/settings.svg'
export { default as SettingsFillIcon } from '@/assets/icons/settings-fill.svg'
export { default as CheckCircleIcon } from '@/assets/icons/check-circle.svg'
export { default as CheckCircleFillIcon } from '@/assets/icons/check-circle-fill.svg'
export { default as FavoriteIcon } from '@/assets/icons/favorite.svg'
export { default as FavoriteFillIcon } from '@/assets/icons/favorite-fill.svg'
export { default as AddIcon } from '@/assets/icons/add.svg'
export { default as DeleteIcon } from '@/assets/icons/delete.svg'
export { default as DeleteFillIcon } from '@/assets/icons/delete-fill.svg'
export { default as ArrowBackIcon } from '@/assets/icons/arrow-back.svg'
export { default as StarIcon } from '@/assets/icons/star.svg'
export { default as StarFillIcon } from '@/assets/icons/star-fill.svg'
export { default as ChevronRightIcon } from '@/assets/icons/chevron-right.svg'
export { default as LogoutIcon } from '@/assets/icons/logout.svg'
export { default as ArrowForwardIOSIcon } from '@/assets/icons/arrow-forward-iOS.svg'
